trigger:
- main

pool:
  name: flm-pool

steps:
- script: echo Hello, world!
  displayName: 'stage-1'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'stage-2'

- script: echo "Wecome to Azure class"
  displayName: 'stage-3'

- script: echo "This is my last stage"
  displayName: 'stage-4'