apiVersion: apps/v1
kind: Deployment

metadata:
  name: mydeploy

spec:
  replicas: 3
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      app: swiggy

  template:

    metadata:
      labels:
        app: swiggy

    spec:

      containers:

      - name: cont1
        image: shaikmustafa/dm

        ports:
        - containerPort: 80


        envFrom:

        - configMapRef:
            name: firstcm

        - configMapRef:
            name: secondcm

        - configMapRef:
            name: thirdcm
