apiVersion: v1
kind: ResourceQuota

metadata:
  name: dev-rq
  namespace: prod

spec:

  hard:

    limits.cpu: "500m"

    requests.cpu: "250m"

    limits.memory: "100Mi"

    requests.memory: "50Mi"
